### ISSUE TITLE
use noEmitHelpers: true & importHelpers: true

### ISSUE THREAD

**Issue by jdanyow** [Microsoft/applicationinsights-channel-js#49]
Inlining the helpers is causing bloat / issues with rollup builds:

![image](https://user-images.githubusercontent.com/1306747/52276680-ab7b3880-2907-11e9-8b5d-cd769674a6ff.png)

**Comment by markwolff** [comment]
Thanks for the report @jdanyow. I'll add them back in for next version

**Comment by jpiyali** [comment]
code moved to applicationinsight-js monorepo under vNext/channels/applicationinsights-channel-js
